//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpi_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baza2Context : DbContext
    {
        public Baza2Context()
            : base("name=Baza2Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<status_> status_ { get; set; }
        public DbSet<typ> typ { get; set; }
        public DbSet<uzytkownik> uzytkownik { get; set; }
        public DbSet<zadanie> zadanie { get; set; }
        public DbSet<algorytm> algorytmSet { get; set; }
    }
}
