//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpi_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownik
    {
        public uzytkownik()
        {
            this.zadanie = new HashSet<zadanie>();
        }
    
        public long id_uzytkownik { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public long typ_id_typ { get; set; }
    
        public virtual typ typ { get; set; }
        public virtual ICollection<zadanie> zadanie { get; set; }
    }
}
