//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpi_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class zadanie
    {
        public long id_zadanie { get; set; }
        public string zadana_liczba { get; set; }
        public string wynik { get; set; }
        public Nullable<int> postep { get; set; }
        public Nullable<System.TimeSpan> czas_rozpoczecie { get; set; }
        public Nullable<System.TimeSpan> czas_zakonczenia { get; set; }
        public Nullable<long> kolejnosc { get; set; }
        public long status__id_status { get; set; }
        public long uzytkownik_id_uzytkownik { get; set; }
    
        public virtual status_ status_ { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
